blocks:
    formbuilder:
        name: Form
        visible: false
        thumbnail: ""
        views:
            basic:
                template: "@EzFormBuilderMigration/landing_page/blocks/formbuilder.html.twig"
                name: Form Block view
        attributes:
            formId:
                type: integer
                name: Form ID
                validators:
                    regexp:
                        options:
                            pattern: '/[0-9]+/'
                        message: 'Invalid ID'
